/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dvd.store;

import static dvd.store.DVDStore.*;
import java.util.ArrayList;

/**
 *
 * @author Kelvin
 */
public class DeleteGui extends javax.swing.JFrame {

ArrayList<Dvd> test = new ArrayList();
    
    /**
     * Creates new form DeleteGui
     */
    public DeleteGui() {
        
        initComponents();
        
        ArrayList<Dvd> dvdsArrayList = new ArrayList(getDvdArrayList());
        movieComboBox.removeAllItems();
        
        for (int i = 0; i < getDvdArrayList().size(); i++) {
            movieComboBox.addItem(dvdsArrayList.get(i).getTitle());
            }

        ArrayList<Customer> customersArrayList = new ArrayList(getCustomerArrayList());
        customerComboBox.removeAllItems();
        
        for (int i = 0; i < getCustomerArrayList().size(); i++) {
            customerComboBox.addItem(customersArrayList.get(i).getPhoneNumber());
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteMovieBtn = new javax.swing.JButton();
        deleteCustomerBtn = new javax.swing.JButton();
        movieComboBox = new javax.swing.JComboBox<>();
        customerComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setTitle("Delete");

        deleteMovieBtn.setText("Delete Movie");
        deleteMovieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieBtnActionPerformed(evt);
            }
        });

        deleteCustomerBtn.setText("Delete Customer");
        deleteCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerBtnActionPerformed(evt);
            }
        });

        movieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        movieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieComboBoxActionPerformed(evt);
            }
        });

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "asdasda" }));

        jLabel1.setText("Movie");

        jLabel2.setText("Customer");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Undo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(deleteMovieBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(deleteCustomerBtn))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomerBtn)
                    .addComponent(deleteMovieBtn))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(jToggleButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieComboBoxActionPerformed

    private void deleteMovieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieBtnActionPerformed
        
        for (int i = 0; i < getDvdArrayList().size(); i++) {
            
            if (getDvdArrayList().get(i).getTitle().equalsIgnoreCase(movieComboBox.getSelectedItem().toString())) {
                deleteDvd(i);
                movieComboBox.removeAllItems();
                
                for (int a = 0; a < getDvdArrayList().size(); a++) {
            movieComboBox.addItem(getDvdArrayList().get(a).getTitle());
            }
            }
            
        }
        
        
    }//GEN-LAST:event_deleteMovieBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        hide();
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerBtnActionPerformed
        
        for (int i = 0; i < getCustomerArrayList().size(); i++) {
            if (getCustomerArrayList().get(i).getPhoneNumber().equalsIgnoreCase(customerComboBox.getSelectedItem().toString())) {
                deleteCustomer(i);
                customerComboBox.removeAllItems();
                for (int j = 0; j < getCustomerArrayList().size(); j++) {
                    customerComboBox.addItem(getCustomerArrayList().get(j).getPhoneNumber());
                    
                }
            }
        }
        
    }//GEN-LAST:event_deleteCustomerBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> customerComboBox;
    private javax.swing.JButton deleteCustomerBtn;
    private javax.swing.JButton deleteMovieBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> movieComboBox;
    // End of variables declaration//GEN-END:variables
}
