/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dvd.store;
import static dvd.store.DVDStore.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Kelvin
 */
public class RentMovie extends javax.swing.JFrame {

    /**
     * Creates new form RentMovie
     */
    public RentMovie() {
        initComponents();
        
        selectMovieComboBox.removeAllItems();
        selectMovieComboBox.addItem("Select a movie to rent");
        
        for (int i = 0; i < getDvdArrayList().size(); i++) {
            selectMovieComboBox.addItem(getDvdArrayList().get(i).getTitle());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectMovieComboBox = new javax.swing.JComboBox<>();
        viewAvailableBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        customerPhoneNumberTf = new javax.swing.JTextField();
        rentBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        addCreditBtn = new javax.swing.JButton();

        setTitle("Rent a movie");

        selectMovieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a movie to rent", "Item 2", "Item 3", "Item 4" }));
        selectMovieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMovieComboBoxActionPerformed(evt);
            }
        });

        viewAvailableBtn.setText("View Available Movies To rent");
        viewAvailableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvailableBtnActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jLabel3.setText("Enter phone number");

        rentBtn.setText("Rent");
        rentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addCreditBtn.setText("Add Credit");
        addCreditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCreditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(54, 54, 54)
                        .addComponent(customerPhoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(addCreditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewAvailableBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectMovieComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rentBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backBtn)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(selectMovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerPhoneNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCreditBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewAvailableBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentBtn)
                    .addComponent(backBtn))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        
        hide();
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void selectMovieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMovieComboBoxActionPerformed

    }//GEN-LAST:event_selectMovieComboBoxActionPerformed

    private void rentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentBtnActionPerformed
        boolean movieReady = false;
        boolean customerReady = false;
        int whichCustomer = 0;
        int whichDvd = 0;
        if((customerPhoneNumberTf.getText().length() > 9 && customerPhoneNumberTf.getText().length() < 11) && !(selectMovieComboBox.getSelectedItem().toString().equalsIgnoreCase("Select a movie to rent"))){
            for (int i = 0; i < getDvdArrayList().size(); i++) {
                if (getDvdArrayList().get(i).getTitle().equalsIgnoreCase(selectMovieComboBox.getSelectedItem().toString()) && getDvdArrayList().get(i).isAvailableForRent()) {
                    movieReady = true;
                    whichDvd = i;
                    break;
                }
            }
            for (int i = 0; i < getCustomerArrayList().size(); i++) {
                if (getCustomerArrayList().get(i).getPhoneNumber().equals(customerPhoneNumberTf.getText()) && getCustomerArrayList().get(i).canRent()) {
                    customerReady = true;
                    whichCustomer = i;
                    break;
                }
            }
            
            if (movieReady && customerReady) {
                
                JOptionPane.showMessageDialog(null, "Successful rent!");
                getCustomerArrayList().get(whichCustomer).addCredit(-(getDvdArrayList().get(whichDvd).getPrice()));
                getCustomerArrayList().get(whichCustomer).setCanRent(false);
                getCustomerArrayList().get(whichCustomer).setMovieRented(getDvdArrayList().get(whichDvd).getTitle());
                getDvdArrayList().get(whichDvd).setAvailableForRent(false);
                
            }else if(movieReady == false){
                JOptionPane.showMessageDialog(null, "The movie is currently being rented");
            }else if(customerReady == false){
                JOptionPane.showMessageDialog(null, "The customer is currently renting another movie");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please enter a valid customer number and select a movie");
        }
        
    }//GEN-LAST:event_rentBtnActionPerformed

    private void addCreditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCreditBtnActionPerformed
        boolean flag = false;
        if(customerPhoneNumberTf.getText().length() > 9 && customerPhoneNumberTf.getText().length() < 11){
        
            for (int i = 0; i < getCustomerArrayList().size(); i++) {
                if (getCustomerArrayList().get(i).getPhoneNumber().equals(customerPhoneNumberTf.getText())) {
                    getCustomerArrayList().get(i).addCredit(Double.parseDouble(JOptionPane.showInputDialog("How much would you like to input?/n" + "Your current credit is R :"+ getCustomerArrayList().get(i).getCredit())));
                    flag = true;
                    
                }
                    
            }
            
            if (flag != true) {
                
                JOptionPane.showMessageDialog(null, "That number does not match any customers");
                    
                }
        
        }else{
        
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number");
            
        }
        
        
        
        
        
    }//GEN-LAST:event_addCreditBtnActionPerformed

    private void viewAvailableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvailableBtnActionPerformed
        String textPlaceholder = "";
        textArea.setText(null);
        
            for (int i = 0; i < getDvdArrayList().size(); i++) {
        
                if (getDvdArrayList().get(i).isAvailableForRent()) {
                
                    textPlaceholder = textPlaceholder + getDvdArrayList().get(i).toString() + "\n \n";
        }
        }
            textArea.setText(textPlaceholder);
        
    }//GEN-LAST:event_viewAvailableBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCreditBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField customerPhoneNumberTf;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rentBtn;
    private javax.swing.JComboBox<String> selectMovieComboBox;
    private javax.swing.JTextArea textArea;
    private javax.swing.JButton viewAvailableBtn;
    // End of variables declaration//GEN-END:variables
}
