/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dvd.store;

import static dvd.store.DVDStore.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelvin
 */
public class ReturnMovieGui extends javax.swing.JFrame {

    /**
     * Creates new form ReturnMovieGui
     */
    public ReturnMovieGui() {
        initComponents();
        
        movieComboBox.removeAllItems();
        movieComboBox.addItem("Select movie to return");
        
        for (int i = 0; i < getDvdArrayList().size(); i++) {
            
            if (!(getDvdArrayList().get(i).isAvailableForRent())) {
                movieComboBox.addItem(getDvdArrayList().get(i).getTitle());
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        returnMovieBtn = new javax.swing.JButton();
        movieComboBox = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        returnMovieBtn.setText("Return Movie");
        returnMovieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMovieBtnActionPerformed(evt);
            }
        });

        movieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnMovieBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(movieComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(returnMovieBtn)
                .addGap(29, 29, 29)
                .addComponent(backBtn)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnMovieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMovieBtnActionPerformed
        
        if (movieComboBox.getSelectedItem().equals("Select movie to return")) {
            
            JOptionPane.showMessageDialog(null, "Please select a movie to return");
            
        }else{
            for (int i = 0; i < getDvdArrayList().size(); i++) {
                
                if (getDvdArrayList().get(i).getTitle().equals(movieComboBox.getSelectedItem())) {
                    
                    getDvdArrayList().get(i).setAvailableForRent(true);
                    
                    for (int j = 0; j < getCustomerArrayList().size(); j++) {
                        
                        if (getCustomerArrayList().get(j).getMovieRented().equals(movieComboBox.getSelectedItem())) {
                            
                            getCustomerArrayList().get(j).setCanRent(true);
                            getCustomerArrayList().get(j).setMovieRented("");
                            
                        }
                        
                    }
                    
                }
            }
        }
        
    }//GEN-LAST:event_returnMovieBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        hide();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> movieComboBox;
    private javax.swing.JButton returnMovieBtn;
    // End of variables declaration//GEN-END:variables
}
